require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnamnesesController do

  # This should return the minimal set of attributes required to create a valid
  # Anamnesis. As you add validations to Anamnesis, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "PersonID" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnamnesesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all anamneses as @anamneses" do
      anamnesis = Anamnesis.create! valid_attributes
      get :index, {}, valid_session
      assigns(:anamneses).should eq([anamnesis])
    end
  end

  describe "GET show" do
    it "assigns the requested anamnesis as @anamnesis" do
      anamnesis = Anamnesis.create! valid_attributes
      get :show, {:id => anamnesis.to_param}, valid_session
      assigns(:anamnesis).should eq(anamnesis)
    end
  end

  describe "GET new" do
    it "assigns a new anamnesis as @anamnesis" do
      get :new, {}, valid_session
      assigns(:anamnesis).should be_a_new(Anamnesis)
    end
  end

  describe "GET edit" do
    it "assigns the requested anamnesis as @anamnesis" do
      anamnesis = Anamnesis.create! valid_attributes
      get :edit, {:id => anamnesis.to_param}, valid_session
      assigns(:anamnesis).should eq(anamnesis)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Anamnesis" do
        expect {
          post :create, {:anamnesis => valid_attributes}, valid_session
        }.to change(Anamnesis, :count).by(1)
      end

      it "assigns a newly created anamnesis as @anamnesis" do
        post :create, {:anamnesis => valid_attributes}, valid_session
        assigns(:anamnesis).should be_a(Anamnesis)
        assigns(:anamnesis).should be_persisted
      end

      it "redirects to the created anamnesis" do
        post :create, {:anamnesis => valid_attributes}, valid_session
        response.should redirect_to(Anamnesis.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved anamnesis as @anamnesis" do
        # Trigger the behavior that occurs when invalid params are submitted
        Anamnesis.any_instance.stub(:save).and_return(false)
        post :create, {:anamnesis => { "PersonID" => "invalid value" }}, valid_session
        assigns(:anamnesis).should be_a_new(Anamnesis)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Anamnesis.any_instance.stub(:save).and_return(false)
        post :create, {:anamnesis => { "PersonID" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested anamnesis" do
        anamnesis = Anamnesis.create! valid_attributes
        # Assuming there are no other anamneses in the database, this
        # specifies that the Anamnesis created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Anamnesis.any_instance.should_receive(:update).with({ "PersonID" => "1" })
        put :update, {:id => anamnesis.to_param, :anamnesis => { "PersonID" => "1" }}, valid_session
      end

      it "assigns the requested anamnesis as @anamnesis" do
        anamnesis = Anamnesis.create! valid_attributes
        put :update, {:id => anamnesis.to_param, :anamnesis => valid_attributes}, valid_session
        assigns(:anamnesis).should eq(anamnesis)
      end

      it "redirects to the anamnesis" do
        anamnesis = Anamnesis.create! valid_attributes
        put :update, {:id => anamnesis.to_param, :anamnesis => valid_attributes}, valid_session
        response.should redirect_to(anamnesis)
      end
    end

    describe "with invalid params" do
      it "assigns the anamnesis as @anamnesis" do
        anamnesis = Anamnesis.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Anamnesis.any_instance.stub(:save).and_return(false)
        put :update, {:id => anamnesis.to_param, :anamnesis => { "PersonID" => "invalid value" }}, valid_session
        assigns(:anamnesis).should eq(anamnesis)
      end

      it "re-renders the 'edit' template" do
        anamnesis = Anamnesis.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Anamnesis.any_instance.stub(:save).and_return(false)
        put :update, {:id => anamnesis.to_param, :anamnesis => { "PersonID" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested anamnesis" do
      anamnesis = Anamnesis.create! valid_attributes
      expect {
        delete :destroy, {:id => anamnesis.to_param}, valid_session
      }.to change(Anamnesis, :count).by(-1)
    end

    it "redirects to the anamneses list" do
      anamnesis = Anamnesis.create! valid_attributes
      delete :destroy, {:id => anamnesis.to_param}, valid_session
      response.should redirect_to(anamneses_url)
    end
  end

end
