require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EdLinksController do

  # This should return the minimal set of attributes required to create a valid
  # EdLink. As you add validations to EdLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "EvidentionID" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EdLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ed_links as @ed_links" do
      ed_link = EdLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ed_links).should eq([ed_link])
    end
  end

  describe "GET show" do
    it "assigns the requested ed_link as @ed_link" do
      ed_link = EdLink.create! valid_attributes
      get :show, {:id => ed_link.to_param}, valid_session
      assigns(:ed_link).should eq(ed_link)
    end
  end

  describe "GET new" do
    it "assigns a new ed_link as @ed_link" do
      get :new, {}, valid_session
      assigns(:ed_link).should be_a_new(EdLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested ed_link as @ed_link" do
      ed_link = EdLink.create! valid_attributes
      get :edit, {:id => ed_link.to_param}, valid_session
      assigns(:ed_link).should eq(ed_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EdLink" do
        expect {
          post :create, {:ed_link => valid_attributes}, valid_session
        }.to change(EdLink, :count).by(1)
      end

      it "assigns a newly created ed_link as @ed_link" do
        post :create, {:ed_link => valid_attributes}, valid_session
        assigns(:ed_link).should be_a(EdLink)
        assigns(:ed_link).should be_persisted
      end

      it "redirects to the created ed_link" do
        post :create, {:ed_link => valid_attributes}, valid_session
        response.should redirect_to(EdLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ed_link as @ed_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        EdLink.any_instance.stub(:save).and_return(false)
        post :create, {:ed_link => { "EvidentionID" => "invalid value" }}, valid_session
        assigns(:ed_link).should be_a_new(EdLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EdLink.any_instance.stub(:save).and_return(false)
        post :create, {:ed_link => { "EvidentionID" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ed_link" do
        ed_link = EdLink.create! valid_attributes
        # Assuming there are no other ed_links in the database, this
        # specifies that the EdLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EdLink.any_instance.should_receive(:update).with({ "EvidentionID" => "1" })
        put :update, {:id => ed_link.to_param, :ed_link => { "EvidentionID" => "1" }}, valid_session
      end

      it "assigns the requested ed_link as @ed_link" do
        ed_link = EdLink.create! valid_attributes
        put :update, {:id => ed_link.to_param, :ed_link => valid_attributes}, valid_session
        assigns(:ed_link).should eq(ed_link)
      end

      it "redirects to the ed_link" do
        ed_link = EdLink.create! valid_attributes
        put :update, {:id => ed_link.to_param, :ed_link => valid_attributes}, valid_session
        response.should redirect_to(ed_link)
      end
    end

    describe "with invalid params" do
      it "assigns the ed_link as @ed_link" do
        ed_link = EdLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EdLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => ed_link.to_param, :ed_link => { "EvidentionID" => "invalid value" }}, valid_session
        assigns(:ed_link).should eq(ed_link)
      end

      it "re-renders the 'edit' template" do
        ed_link = EdLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EdLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => ed_link.to_param, :ed_link => { "EvidentionID" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ed_link" do
      ed_link = EdLink.create! valid_attributes
      expect {
        delete :destroy, {:id => ed_link.to_param}, valid_session
      }.to change(EdLink, :count).by(-1)
    end

    it "redirects to the ed_links list" do
      ed_link = EdLink.create! valid_attributes
      delete :destroy, {:id => ed_link.to_param}, valid_session
      response.should redirect_to(ed_links_url)
    end
  end

end
