require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MasterMedicalFacilitiesController do

  # This should return the minimal set of attributes required to create a valid
  # MasterMedicalFacility. As you add validations to MasterMedicalFacility, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "Code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MasterMedicalFacilitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all master_medical_facilities as @master_medical_facilities" do
      master_medical_facility = MasterMedicalFacility.create! valid_attributes
      get :index, {}, valid_session
      assigns(:master_medical_facilities).should eq([master_medical_facility])
    end
  end

  describe "GET show" do
    it "assigns the requested master_medical_facility as @master_medical_facility" do
      master_medical_facility = MasterMedicalFacility.create! valid_attributes
      get :show, {:id => master_medical_facility.to_param}, valid_session
      assigns(:master_medical_facility).should eq(master_medical_facility)
    end
  end

  describe "GET new" do
    it "assigns a new master_medical_facility as @master_medical_facility" do
      get :new, {}, valid_session
      assigns(:master_medical_facility).should be_a_new(MasterMedicalFacility)
    end
  end

  describe "GET edit" do
    it "assigns the requested master_medical_facility as @master_medical_facility" do
      master_medical_facility = MasterMedicalFacility.create! valid_attributes
      get :edit, {:id => master_medical_facility.to_param}, valid_session
      assigns(:master_medical_facility).should eq(master_medical_facility)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MasterMedicalFacility" do
        expect {
          post :create, {:master_medical_facility => valid_attributes}, valid_session
        }.to change(MasterMedicalFacility, :count).by(1)
      end

      it "assigns a newly created master_medical_facility as @master_medical_facility" do
        post :create, {:master_medical_facility => valid_attributes}, valid_session
        assigns(:master_medical_facility).should be_a(MasterMedicalFacility)
        assigns(:master_medical_facility).should be_persisted
      end

      it "redirects to the created master_medical_facility" do
        post :create, {:master_medical_facility => valid_attributes}, valid_session
        response.should redirect_to(MasterMedicalFacility.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved master_medical_facility as @master_medical_facility" do
        # Trigger the behavior that occurs when invalid params are submitted
        MasterMedicalFacility.any_instance.stub(:save).and_return(false)
        post :create, {:master_medical_facility => { "Code" => "invalid value" }}, valid_session
        assigns(:master_medical_facility).should be_a_new(MasterMedicalFacility)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MasterMedicalFacility.any_instance.stub(:save).and_return(false)
        post :create, {:master_medical_facility => { "Code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested master_medical_facility" do
        master_medical_facility = MasterMedicalFacility.create! valid_attributes
        # Assuming there are no other master_medical_facilities in the database, this
        # specifies that the MasterMedicalFacility created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MasterMedicalFacility.any_instance.should_receive(:update).with({ "Code" => "MyString" })
        put :update, {:id => master_medical_facility.to_param, :master_medical_facility => { "Code" => "MyString" }}, valid_session
      end

      it "assigns the requested master_medical_facility as @master_medical_facility" do
        master_medical_facility = MasterMedicalFacility.create! valid_attributes
        put :update, {:id => master_medical_facility.to_param, :master_medical_facility => valid_attributes}, valid_session
        assigns(:master_medical_facility).should eq(master_medical_facility)
      end

      it "redirects to the master_medical_facility" do
        master_medical_facility = MasterMedicalFacility.create! valid_attributes
        put :update, {:id => master_medical_facility.to_param, :master_medical_facility => valid_attributes}, valid_session
        response.should redirect_to(master_medical_facility)
      end
    end

    describe "with invalid params" do
      it "assigns the master_medical_facility as @master_medical_facility" do
        master_medical_facility = MasterMedicalFacility.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MasterMedicalFacility.any_instance.stub(:save).and_return(false)
        put :update, {:id => master_medical_facility.to_param, :master_medical_facility => { "Code" => "invalid value" }}, valid_session
        assigns(:master_medical_facility).should eq(master_medical_facility)
      end

      it "re-renders the 'edit' template" do
        master_medical_facility = MasterMedicalFacility.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MasterMedicalFacility.any_instance.stub(:save).and_return(false)
        put :update, {:id => master_medical_facility.to_param, :master_medical_facility => { "Code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested master_medical_facility" do
      master_medical_facility = MasterMedicalFacility.create! valid_attributes
      expect {
        delete :destroy, {:id => master_medical_facility.to_param}, valid_session
      }.to change(MasterMedicalFacility, :count).by(-1)
    end

    it "redirects to the master_medical_facilities list" do
      master_medical_facility = MasterMedicalFacility.create! valid_attributes
      delete :destroy, {:id => master_medical_facility.to_param}, valid_session
      response.should redirect_to(master_medical_facilities_url)
    end
  end

end
